USE Bank_db;
CREATE TABLE SocStatuses
(
	Id INT NOT NULL,
	SocStatusName VARCHAR(15) NOT NULL,

	CONSTRAINT PK_SocStatusId PRIMARY KEY(Id)
)
CREATE TABLE Client
(
	Id INT IDENTITY(1,1)  NOT NULL,
	ClientName VARCHAR(30) NOT NULL,
	SocStatusId INT NOT NULL,

	CONSTRAINT PK_ClientId PRIMARY KEY(Id),
	CONSTRAINT FK_SocStatusId FOREIGN KEY (socStatusId)
		REFERENCES SocStatuses(Id)
)
CREATE TABLE Cities
(
	Id INT IDENTITY(1,1)  NOT NULL,
	CityName VARCHAR(30) NOT NULL,

	CONSTRAINT PK_CityId PRIMARY KEY(Id)
)

CREATE TABLE Bank
(
	Id INT IDENTITY(1,1)  NOT NULL,
	BankName VARCHAR(30) NOT NULL,

	CONSTRAINT PK_BankId PRIMARY KEY(Id),


)
CREATE TABLE Filials
(
	Id INT IDENTITY(1,1)  NOT NULL,
	BankId INT NOT NULL,
	CityId INT NOT NULL,

	CONSTRAINT PK_FilialId PRIMARY KEY(Id),
	CONSTRAINT FK_CityId FOREIGN KEY (CityId)
		REFERENCES Cities(Id),
	CONSTRAINT FK_FilialsBankId FOREIGN KEY (BankId)
		REFERENCES bank(Id)
)
CREATE TABLE Account
(
	Id INT IDENTITY(1,1)  NOT NULL,
	ClientId INT NOT NULL,
	Score MONEY DEFAULT 0,
	BankId INT NOT NULL,

	CONSTRAINT PK_AccId PRIMARY KEY(Id),
	CONSTRAINT FK_ClientAccId FOREIGN KEY (ClientId)
		REFERENCES Client(Id),
	CONSTRAINT FK_BankId FOREIGN KEY (BankId)
	REFERENCES bank(Id)


)
CREATE TABLE CreditCard
(
	Id INT IDENTITY(1,1)  NOT NULL,
	CashOnCard MONEY DEFAULT 0,
	AccountId INT REFERENCES Account(Id),

	CONSTRAINT PK_CardId PRIMARY KEY(Id),

)


